In [67]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [68]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [69]:
print(x)

[['Malaysia' 30.0 50000.0]
 ['Thailand' 50.0 35000.0]
 ['Vietnam' 70.0 55000.0]
 ['Indonesia' 45.0 65000.0]
 ['Japan' 78.0 nan]
 ['Vietnam' 76.0 40000.0]
 ['Indonesia' nan 66000.0]
 ['Malaysia' 40.0 60000.0]
 ['Filipina' 67.0 nan]
 ['Indonesia' 55.0 40000.0]
 ['Vietnam' 45.0 35000.0]
 ['Singapura' nan 66000.0]
 ['Japan' 33.0 60000.0]
 ['Indonesia' 80.0 nan]]


In [70]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No'
 'Yes']


In [71]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] =imputer.transform(x[:,1:3])

In [72]:
print(x)

[['Malaysia' 30.0 50000.0]
 ['Thailand' 50.0 35000.0]
 ['Vietnam' 70.0 55000.0]
 ['Indonesia' 45.0 65000.0]
 ['Japan' 78.0 52000.0]
 ['Vietnam' 76.0 40000.0]
 ['Indonesia' 55.75 66000.0]
 ['Malaysia' 40.0 60000.0]
 ['Filipina' 67.0 52000.0]
 ['Indonesia' 55.0 40000.0]
 ['Vietnam' 45.0 35000.0]
 ['Singapura' 55.75 66000.0]
 ['Japan' 33.0 60000.0]
 ['Indonesia' 80.0 52000.0]]


In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [74]:
print(x)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 50000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 50.0 35000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 70.0 55000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 45.0 65000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 78.0 52000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 76.0 40000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 55.75 66000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 40.0 60000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 67.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 55.0 40000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 45.0 35000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 55.75 66000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 33.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 80.0 52000.0]]


In [75]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [76]:
print(y)

[0 1 0 0 1 1 0 0 1 1 0 0 0 1]


In [77]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [78]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 70.0 55000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 45.0 35000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 78.0 52000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 50.0 35000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 33.0 60000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 50000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 80.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 55.0 40000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 67.0 52000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 55.75 66000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 76.0 40000.0]]


In [79]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 45.0 65000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 40.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 55.75 66000.0]]


In [80]:
print(y_train)

[0 0 1 1 0 0 1 1 1 0 1]


In [81]:
print(y_test)

[0 0 0]


In [82]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [83]:
print(x_train)

[[0.0 0.0 0.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  1.632993161855452 0.706622746604209 0.6395770010475138]
 [0.0 0.0 0.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  1.632993161855452 -0.7852870830783816 -1.4296427082238539]
 [0.0 0.0 1.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 1.1840338921026379 0.3291940446568087]
 [0.0 0.0 0.0 -0.316227766016838 -0.31622776601683794 3.16227766016838
  -0.6123724356957945 -0.48690511714186346 -1.4296427082238539]
 [0.0 0.0 1.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 -1.5014038013260251 1.1568819283653557]
 [0.0 0.0 0.0 3.16227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 -1.680432980887936 0.12227207372967193]
 [0.0 1.0 0.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 1.3033866784772452 0.3291940446568087]
 [0.0 1.0 0.0 -0.316227766016838 -0.31622776601683794 -0.3162277

In [84]:
print(x_test)

[[0.0 1.0 0.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 -0.7852870830783816 1.6741868556831976]
 [0.0 0.0 0.0 3.16227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 -1.0836690490148997 1.1568819283653557]
 [0.0 1.0 0.0 -0.316227766016838 -0.31622776601683794 -0.316227766016838
  -0.6123724356957945 -0.14376585631486766 1.777647841146766]]
